# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn install

    - name: Get Release ID
      id: set_ids
      run: |
        version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
        upload_url=$(curl -s "https://api.github.com/repos/razvvan/ds-at-home/releases" | jq '.[] | select(.tag_name=="$version") | .upload_url')

        echo "::set-output name=V_TAG::$version"
        echo "::set-output name=upload_url::$upload_url"

    - run: |
        echo ${{ steps.set_ids.outputs.upload_url }}

    - id: dist-builder
      run: |
        version=${{ steps.set_ids.outputs.V_TAG }}
        EXTRAMETADATA="-c.extraMetadata.version=$version" yarn run dist-rpi

    - name: Upload Release Asset (rpi)
      id: upload-release-asset-rpi
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_ids.outputs.upload_url }}
        asset_path: ./dist/ds-at-home_${{ steps.set_ids.outputs.V_TAG }}_arm64.deb
        asset_name: ds-at-home_${{ steps.set_ids.outputs.V_TAG }}_arm64.deb
        asset_content_type: application/vnd.debian.binary-package
