name: Build rPI version

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn install

    - name: Build
      run: |
        version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
        EXTRAMETADATA="-c.extraMetadata.version=$version" yarn run dist-rpi

    - name: Upload
      run: |
        version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        gh release upload "v"$version ./dist/ds-at-home_$version_arm64.deb
